name = "observatory"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "OBSERVATORY_CACHE"
id = "cf6fe79d1a254877937edb081d768fed"
preview_id = "c48ee92a03584538a3479c307dfd7093"
